Origin param
MapColonies/GpkgMerger pull request #12
Opened 2022-06-01 12:26 UTC by cl-shaharshavit-rnd

2022-06-01 13:17 UTC, asafMasa commented on MergerLogic/DataTypes/Data.cs
> +        public static Data CreateDatasource(string type, string path, int batchSize, bool isBase, Extent extent, int maxZoom, int minZoom = 0, bool isOneXone = false, TileGridOrigin? origin = null)
why it's null? why you don't set the origin to a default on startup and prevent all the "if null" checks?

2022-06-01 13:30 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Data.cs
> +                this._getTile = (z, x, y) =>
static is bad for mocking

2022-06-01 13:37 UTC, cl-shaharshavit-rnd commented on MergerCli/SourceParser.cs
> +                TileGridOrigin? origin = null;
done

2022-06-01 13:53 UTC, shimoncohen requested changes

2022-06-01 14:14 UTC, asafMasa approved these changes

2022-06-02 05:19 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
>                                      merge sources: {programName} <batch_size> <base source> <addiotional source> [<another source source>...]
fixed

2022-06-02 05:19 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +                                            <'xyz' / 'wmts' / 'tms'> <url template> <bbox - in format 'minX,minY,maxX,maxY'> <min zoom> <max zoom> [--1x1] [--UL / --LL]
added

2022-06-02 05:19 UTC, cl-shaharshavit-rnd commented on MergerCli/SourceParser.cs
> +            if (optionalParams.Contains("--UL"))
done

2022-06-02 05:19 UTC, cl-shaharshavit-rnd commented on MergerCli/SourceParser.cs
> +            if (optionalParams.Contains("--UL"))
fixed

2022-06-02 05:19 UTC, cl-shaharshavit-rnd commented on MergerCli/SourceParser.cs
> +                origin = TileGridOrigin.UPPER_LEFT;
fixed

2022-06-02 07:05 UTC, merged