chore: gpkg data source unit test
MapColonies/GpkgMerger pull request #21
Opened 2022-06-26 13:20 UTC by cl-shaharshavit-rnd

2022-06-26 14:08 UTC, asafMasa requested changes

2022-06-27 05:46 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +                    if (file.Directory != null)
no, the directory.create already does that

2022-06-27 06:00 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/DataTypes/Fs.cs
> +        {
deleted the file

2022-06-27 06:59 UTC, asafMasa approved these changes

2022-06-29 12:15 UTC, shimoncohen requested changes

2022-06-29 13:45 UTC, cl-shaharshavit-rnd commented on .github/workflows/test.yaml
> +    runs-on: ubuntu-latest
it is latest ubuntu in boiler plate and every other service

2022-06-29 13:46 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/utils/DynamicDataGenerator.cs
> +                yield break;
this is the exit condition of the iterator so break is required

2022-06-29 13:47 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/DataTypes/GpkgTest.cs
> +        private Mock<IOneXOneConvertor> _OneXOneConvertorMock;
wont fix in this pr to prevent conflicts.
already fixed in next pr

2022-06-29 13:48 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/DataTypes/GpkgTest.cs
> +            bool useCords)
wont fix in this pr to prevent conflicts.
already fixed in next pr

2022-06-29 13:48 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/DataTypes/GpkgTest.cs
> +            bool useCords)
wont fix in this pr to prevent conflicts.
already fixed in next pr

2022-06-29 13:54 UTC, cl-shaharshavit-rnd commented on MergerLogicUnitTests/DataTypes/GpkgTest.cs
> +            var extent = new Extent() { minX = -180, minY = -90, maxX = 180, maxY = 90 };
i dont want to have any shared data between the tests to prevent braking all of them when modifying 1 (for example if the tested code modify it)

2022-06-29 14:11 UTC, shimoncohen approved these changes

2022-06-30 04:20 UTC, merged