feat: gpkg grid validation
MapColonies/GpkgMerger pull request #39
Opened 2022-07-21 08:33 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-07-21 09:24 UTC, asafMasa requested changes
💯

2022-07-21 09:24 UTC, asafMasa commented on MergerLogic/Utils/GpkgUtils.cs
> +                        return false;
add log on failed check

2022-07-21 09:24 UTC, asafMasa commented on MergerLogic/Utils/GpkgUtils.cs
> +                                return false;
add log on failed check (table, zoom, expected fields vs actual fields)

2022-07-24 04:33 UTC, cl-shaharshavit-rnd commented on MergerLogic/Extensions/DoubleExtenstion.cs
> +            return (Math.Abs(initialValue - value) < maximumDifferenceAllowed);
doesn't really matters in that case.
Updated anyways

2022-07-24 06:28 UTC, asafMasa approved these changes

2022-07-24 06:30 UTC, asafMasa approved these changes

2022-07-24 06:31 UTC, merged