fix: added node affinity use condition
MapColonies/GpkgMerger pull request #42
Opened 2022-07-24 11:47 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-07-24 13:41 UTC, asafMasa requested changes

2022-07-24 13:41 UTC, asafMasa commented on helm/values.yaml
> +  useNodeAffinity: true
default false

2022-07-25 07:51 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  useNodeAffinity: true
fixed

2022-07-25 08:37 UTC, asafMasa approved these changes

2022-07-25 08:40 UTC, merged