chore: start with empty configuration for task and job types
MapColonies/GpkgMerger pull request #46
Opened 2022-08-14 15:09 UTC by shimoncohen

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2022-08-14 20:11 UTC, asafMasa approved these changes

2022-08-15 05:26 UTC, CL-SHLOMIKONCHA approved these changes

2022-08-15 07:35 UTC, cl-shaharshavit-rnd requested changes

2022-08-15 07:35 UTC, cl-shaharshavit-rnd commented on MergerService/src/run.cs
> +                this._logger.LogInformation("No tasks configured, please provide job and task types");
that's critical error it is not info and it should probably throw and kill the app

2022-08-15 08:17 UTC, cl-shaharshavit-rnd approved these changes

2022-08-15 08:19 UTC, asafMasa approved these changes

2022-08-15 08:27 UTC, merged