feat: added http retry support
MapColonies/GpkgMerger pull request #53
Opened 2022-08-18 05:47 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-08-18 07:53 UTC, shimoncohen requested changes

2022-08-18 07:53 UTC, shimoncohen commented on MergerLogic/Extensions/ServiceCollectionExtensions.cs
> +                ;
Move to previous line.

2022-08-18 10:49 UTC, asafMasa approved these changes

2022-08-22 07:15 UTC, shimoncohen approved these changes

2022-08-22 07:54 UTC, merged