feat: support resume
MapColonies/GpkgMerger pull request #9
Opened 2022-05-18 14:22 UTC by cl-shaharshavit-rnd

2022-05-19 09:04 UTC, shimoncohen requested changes

2022-05-19 09:04 UTC, shimoncohen commented on MergerLogic/DataTypes/Fs.cs
> +        private int complatedTiles;
completedTiles

2022-05-19 09:04 UTC, shimoncohen commented on MergerLogic/DataTypes/Fs.cs
> +            this.complatedTiles = 0;
completedTiles

2022-05-19 09:04 UTC, shimoncohen commented on MergerLogic/DataTypes/Fs.cs
> +            //un commont to make this function work at any point of the run and not only after the source initialization
*comment

2022-05-19 09:29 UTC, asafMasa requested changes

2022-05-19 09:29 UTC, asafMasa commented on MergerLogic/DataTypes/Fs.cs
> +            //un commont to make this function work at any point of the run and not only after the source initialization
un commont - spelling

2022-05-19 09:29 UTC, asafMasa commented on MergerCli/utils/BatchStatusManager.cs
> +        internal class LayerStatus
i don't like the you define 2 classes at the same file.
maybe try to separate this class definition to a different file

2022-05-19 09:29 UTC, asafMasa commented on MergerCli/Proccess.cs
> +                //fix resume progress bug for gpkg and fs, fixing it for s3 reuries storing additional data.
reuries - spelling - requires?

2022-05-19 09:29 UTC, asafMasa commented on MergerCli/utils/BatchStatusManager.cs
> +        public void ComplateLayer(string layer)
spelling

2022-05-22 04:44 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +                                    status file named 'status.json' will be created in running directory on incomplate merges
fixed

2022-05-22 04:44 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +            AssemblyLoadContext.Default.Unloading += delegate { OnFailure(); };
added

2022-05-22 04:45 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +                    if (batchStatusManager.IsLayerComplated(newPath))
added

2022-05-22 04:45 UTC, cl-shaharshavit-rnd commented on MergerCli/utils/BatchStatusManager.cs
> +        public void ComplateLayer(string layer)
fixed

2022-05-22 04:46 UTC, cl-shaharshavit-rnd commented on MergerCli/utils/BatchStatusManager.cs
> +        public bool IsLayerComplated(string layer)
fixed

2022-05-22 04:46 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +                                    Resume: {programName} <path to status file>.
???

2022-05-22 04:47 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +        private int complatedTiles;
fixed

2022-05-22 04:47 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +            this.complatedTiles = 0;
fixed

2022-05-22 04:48 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +            //un commont to make this function work at any point of the run and not only after the source initialization
fixed

2022-05-22 04:48 UTC, cl-shaharshavit-rnd commented on MergerCli/utils/BatchStatusManager.cs
> +            public string? BathIdentifier { get; set; }
fixed

2022-05-22 04:48 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +        private int complatedTiles;
fixed

2022-05-22 04:49 UTC, cl-shaharshavit-rnd commented on MergerLogic/DataTypes/Fs.cs
> +            //un commont to make this function work at any point of the run and not only after the source initialization
fixed

2022-05-22 04:49 UTC, cl-shaharshavit-rnd commented on MergerCli/Proccess.cs
> +                //fix resume progress bug for gpkg and fs, fixing it for s3 reuries storing additional data.
fixed

2022-05-22 04:50 UTC, cl-shaharshavit-rnd commented on MergerCli/utils/BatchStatusManager.cs
> +        public void ComplateLayer(string layer)
fixed

2022-05-22 05:49 UTC, cl-shaharshavit-rnd commented on MergerCli/Program.cs
> +                                    Resume: {programName} <path to status file>.
added

2022-05-22 06:48 UTC, asafMasa approved these changes

2022-05-22 09:14 UTC, shimoncohen approved these changes

2022-05-22 10:41 UTC, merged