chore: handle new target source
MapColonies/GpkgMerger pull request #92
Opened 2022-12-14 13:42 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2022-12-14 14:41 UTC, asafMasa requested changes
👍

2022-12-14 15:18 UTC, CL-SHLOMIKONCHA commented on MergerService/MergerService.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.14.0" />
fixed

2022-12-14 15:19 UTC, CL-SHLOMIKONCHA commented on .idea/.idea.GpkgMerger.dir/.idea/.gitignore
> +# Default ignored files
fixed

2022-12-14 15:29 UTC, asafMasa approved these changes

2022-12-15 08:34 UTC, shimoncohen approved these changes

2022-12-15 08:34 UTC, shimoncohen commented on MergerService/Utils/TaskUtils.cs
> +            this._jsonSerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
Intresting.

2022-12-15 09:16 UTC, merged